name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create keys.js
        run: |
          echo "window.apiKey = '${{ secrets.API_KEY }}';" > keys.js
          echo "window.playlistId = '${{ secrets.PLAYLIST_ID }}';" >> keys.js

      - name: Prepare dist
        run: |
          rm -rf dist
          mkdir dist

          cp index.html dist/
          cp style.css dist/
          cp player.js dist/
          cp watch.js dist/
          cp watch.html dist/

          # УБРАЛИ ПРОБЛЕМНЫЙ ФАЙЛ
          # cp keys-module.js dist/

          cp keys-global.js dist/ || true
          cp keys.js dist/

          cp favicon.svg dist/
          cp rucka.png dist/
          cp radio.brodiaga.jpg dist/ || true
          cp -r img dist/ || true
          cp -r assets dist/ || true
          cp -r pages dist/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
