name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure site folder exists
        run: |
          mkdir -p site

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > site/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> site/sitemap.xml

          # Все HTML-файлы внутри site
          find site -name "*.html" | while read file; do
            clean="${file#site/}"
            url="https://radio.brodiaga.com/$clean"
            echo "<url><loc>$url</loc></url>" >> site/sitemap.xml
          done

          PLAYLIST_IDS="PLFaaHMye1-yZBk5Z4EzxkzRf9j1m_NX-E PLFaaHMye1-yapSv6zpzE2d3CzmigR-yGg PLFaaHMye1-yakkCa3Un2YDFhoZjLt_qSI PLFaaHMye1-yZbC7gtMl55N_Gv45wBjS2k PLFaaHMye1-yZjsgMXCngGbqPKVLZfT8vR"

          for playlist in $PLAYLIST_IDS; do
            curl -s "https://www.googleapis.com/youtube/v3/playlistItems?key=${{ secrets.API_KEY }}&playlistId=$playlist&part=contentDetails&maxResults=50" > playlist.json

            cat playlist.json | jq -r '.items[].contentDetails.videoId' | while read id; do
              echo "<url><loc>https://radio.brodiaga.com/watch.html?id=$id</loc></url>" >> site/sitemap.xml
            done
          done

          echo '</urlset>' >> site/sitemap.xml

      - name: Upload sitemap artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy sitemap to GitHub Pages
        uses: actions/deploy-pages@v4
