name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          find . -name "*.html" | while read file; do
            clean="${file#./}"
            url="https://radio.brodiaga.com/$clean"
            echo "<url><loc>$url</loc></url>" >> sitemap.xml
          done

          PLAYLIST_IDS="PLFaaHMye1-yZBk5Z4EzxkzRf9j1m_NX-E PLFaaHMye1-yapSv6zpzE2d3CzmigR-yGg PLFaaHMye1-yakkCa3Un2YDFhoZjLt_qSI PLFaaHMye1-yZbC7gtMl55N_Gv45wBjS2k PLFaaHMye1-yZjsgMXCngGbqPKVLZfT8vR"

          for playlist in $PLAYLIST_IDS; do
            curl -s "https://www.googleapis.com/youtube/v3/playlistItems?key=${{ secrets.API_KEY }}&playlistId=$playlist&part=contentDetails&maxResults=50" > playlist.json

            jq -r '.items[].contentDetails.videoId' playlist.json | while read id; do
              echo "<url><loc>https://radio.brodiaga.com/watch.html?id=$id</loc></url>" >> sitemap.xml
            done
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit sitemap
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap" || echo "No changes"
          git push
